config/routes.rb
    resources :roles, only: [:index]
    resources :properties, only: [:create, :index]
    resources :in_app_notifications, only: [:index]
    resources :departments, only: [:index]
    resources :public_areas, only: [:index, :show] do
      resources :checklist_items, only: [ :index ]
      collection do
        get :checklist_items
      end
    end
    resources :rooms, only: [] do
      collection do
        get :checklist_items
      end
    end
    resources :acknowledgements, only: [:index, :create, :show] do
      collection do
        get :sent
        get :received
      end
    end
    resources :feeds, only: [:index, :create, :show, :update] do
      resources :work_orders, only: [ :create ]
      collection do
        get :broadcasts
        get :follow_ups
      end
    end
    get '/broadcasts' => 'feeds#broadcasts'
    resources :chats, only: [:create, :update, :index] do
      collection do
        get :group_only
        get :private_only
      end
      member do
        get :messages
      end
    end
    resources :chat_messages, only: [ :index, :create, :show ] do
      resources :work_orders, only: [ :create ]
      collection do
        get :updates
        put :mark_read_mass
      end
      member do
        put :mark_read
      end
    end
    resources :users, only: [:index, :show, :update, :create] do
      member do
        get :roles_and_departments
        put :confirm
      end
      collection do
        post :invite
        post :multi_invite
        get :request_confirm
      end
    end
    resources :mentions, only: [:index, :update] do
      collection do
        put :snooze
        put :unsnooze
        put :clear
      end
    end
    resources :work_orders, only: [:index, :create, :show, :update] do
      member do
        put :close
      end

      collection do
        get :assignable_users
      end
    end
    resources :checklist_items, only: [:index]
    resources :chat_mentions, only: [:update]
    resource :passwords, only: [:create, :update]
    resources :permissions, only: [:index]
    resources :push_notification_settings, only: [:index]
    resource :push_notification_settings, only: [:update]
    get '/s3_sign', to: 'auth#s3_sign'
    resources :check_for_app_update, only: [:index]
  end
  get '/login/:auth_token' => 'login#create'
  get '/how-to-videos' => 'videos#how_to_videos'

  resources :chats, only: [:show, :index, :new, :create]
  resources :messages, controller: :chats, only: [ :show, :index, :new, :create ]
  resources :chat_messages, only: [:create]
  resources :task_lists, only: [:index, :show, :new, :edit, :create, :update] do
    collection do
      get :activities
      get :setup
    end
  end

  namespace :corporate do
    root to: 'pages#dashboard'
    resources :settings, only: [:index]
    resources :property_connections, only: [:show, :update]
    resources :purchase_requests, only: [:edit, :update], path: 'requests'
    get '/spend_budget_by_hotel_data' => 'pages#spend_budget_by_hotel', as: 'spend_budget_by_hotel_data'
    get '/work_order_clouds' => 'pages#work_order_clouds', as: 'work_order_clouds'
    get '/open_work_order_by_hotel' => 'pages#open_work_orders_by_hotel', as: 'open_work_orders_by_hotel'
  end

  namespace :maintenance do
    root to: 'pages#dashboard' # probably need to move it under /dashboard, @HUGO
    get :setup, to: 'setup#index', as: :setup
    get '/setup/rooms', to: 'setup#rooms', as: :setup_rooms
    get '/setup/public_areas', to: 'setup#public_areas', as: :setup_public_areas
    get '/setup/equipment', to: 'setup#equipment', as: :setup_equipment
    resources :rooms, only: [:show, :index, :create, :update] do
      get :inspection, on: :collection
      get :inspect, on: :member
    end
    resources :checklist_items, only: [:index, :create, :update,:destroy]
    resources :cycles, only: [:create] do
      post :create_next, on: :collection
    end
    resources :checklist_item_maintenances, only: [:index, :create, :destroy] do
      member do
        post :inspect
        delete :cancel_inspect
      end

      collection do
        get :equipment
      end
    end
    resources :public_areas, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :checklist_items
        get :inspection
      end
      get :inspect, on: :member
    end
    resources :records, only: [:index, :update, :show, :destroy] do
      member do
        post :complete_inspection
        post :cancel_inspection
      end
    end
    resources :work_orders do
      get :export, on: :collection
    end
    resources :materials, only: [:index, :create, :update, :destroy]
    resources :equipment_types, only: [:index, :create, :update, :destroy] do
      resources :equipment_checklist_items, only: [:index, :create, :show, :update, :destroy]
    end
    resources :equipments, only: [:index, :show, :create, :update, :destroy]

    get '/week_vs_completed_rooms_data' => 'pages#week_vs_completed_rooms_data', as: 'week_vs_completed_rooms_data'
    get '/pm_room_progress_data' => 'pages#pm_room_progress_data', as: 'pm_room_progress_data'
  end

  namespace :admin do
    root to: 'pages#dashboard'
    resources :users, only: [:edit, :update]
    resources :customers, only: [:index, :new, :create, :show] do
      member do
        post :impersonate
      end
    end
  end

  devise_for :admins, path: 'admin', controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords'
                      }

  resource :corporate_connections

  get :spend_vs_budgets_data, to: 'pages#spend_vs_budgets_data'
  get :s3_sign, to: 'pages#s3_sign'

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'pages#dashboard', as: :admin_authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
    namespace :users, as: :user do
      put "/confirm" => "confirmations#confirm", as: :confirm
      put '/switch_current_property', to: 'sessions#switch_current_property', as: :switch_current_property
      resource :registration, only: [:edit, :update]
    end
  end
  resources :property_settings, path: 'settings', only: [:index]
  resources :categories, :locations, :lists do
    get 'rearrange', on: :member
    get 'destroy', on: :collection, as: 'destroy'
  end
  resources :items do
    collection do
      get 'start_order'
      get 'edit_multiple_tags'
      put 'update_multiple_tags'
      get :new_import
      post :import
      get 'destroy', as: 'destroy'
    end
  end
  resources :permissions, only: [:index] do
    collection do
      post 'update_all'
    end
  end
  resources :properties, only: [:show, :index, :update]
  resources :tags do
    get 'rearrange', on: :member
  end
  resources :purchase_orders, except: [:edit, :new, :create], path: 'orders' do
    member do
      post :send_fax, to: 'fax#create'
      get :fax_status, to: 'fax#show'
      post :update_fax, to: 'fax#update'
      post :send_email, to: 'email#create'
      post :send_vpt, to: 'vpt#create'
      get :print
    end
  end
  resources :purchase_receipts, only: [:new, :create], path: 'receipts'
  resources :purchase_requests, path: 'requests' do
    member do
      get :inventory_print
    end
  end
  resources :users do
    member do
      get :change_password
    end

    collection do
      post :valid_username
      post :confirm_username
    end
  end
  resources :work_order_messages, controller: :messages
  resources :budgets
  resources :schedules, only: [:create, :update, :destroy]
  resources :occurrences, only: [:create]

  resources :reports do
    member do
      put :favorite
    end
    collection do
      get :favorites
      #get *Report.pluck(:permalink).map{|p| p + '_data'} if Report.any?
      get :trending_cloud
      scope :render do
        get :vendor_spend
        get :category_spend
        get :items_consumption
        get :item_orders_chart_data
        get :items_spend
        get :item_price_variance
        get :inventory_vs_ordering
        get :maintenance_work_orders
        get :pm_productivity_report
        get :maintenance_pm_productivity_data
        get :room_pm_progress_data
        get :work_order_productivity_data
        get :guest_room_pm_analysis
        get :public_area_pm_analysis
        get :equipment_pm_analysis
        get :work_order_trendings
      end
    end
  end


  resources :vendors
  resources :room_types
  resources :departments
  resources :notifications
  resources :activities, only: [:index]
  resources :join_invitations do
    get 'accept', on: :member
  end
  # resources :guest_logs do
  #   get 'like', on: :member
  #   post 'set_alarm', on: :collection
  #   get 'check_alarm', on: :member
  #   delete 'remove_alarm', on: :member
  # end

  namespace :engage do
    get :dashboard, to: 'dashboard#index', as: :dashboard
    resources :messages, only: [:index, :create, :update]
    resources :entities, only: [:index, :create, :update, :destroy]
  end

  post 'punchout/:property_id/:vendor_id/shopping_cart', to: "punchout#shopping_cart", as: 'punchout_shopping_cart'
  get 'punchout/:property_id/:vendor_id', to: "punchout#create", as: 'start_punchout'

  get 'analytics', to: "analytics#index"
  get 'forecasts/(week/:year/:month/:day)', to: "forecasts#index", as: "forecasts"
  put 'forecast', to: "forecasts#update", as: "update_forecast"

  get '/fax', to: 'fax#show'
  post '/fax', to: 'fax#create'
  post '/phaxio', to: 'fax#update'
  get 'dashboard', to: 'pages#dashboard', :as => :dashboard
  get 'pages/home'
  # authenticated :user do
  #   root to: 'pages#dashboard'
  # end

  resource :translation, controller: :translation, only: [:create]

  #root to: 'users/sessions#new'
  if Rails.env.development? or Rails.env.qa?
    mount MailerPreview => 'mailer_view'
    mount Sidekiq::Web, at: '/sidekiq'

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController

  def index
    @users = User.general.reorder(:name).page params[:page]
  end

  def new
    add_breadcrumb 'Setup New Customer'
  end

  def impersonate
    @user = User.find params[:id]
    sign_in @user, scope: :user

    redirect_to authenticated_root_path
  end

  def create
    corporate_params = params[:corporate].extract! :name, :username, :useremail
    properties = params[:corporate].delete :properties
    message = {}
    ActiveRecord::Base.transaction do
      @corporate = Corporate.create_corporate corporate_params
      message[:alert] = 'User is part of another Corporate site. Please use another email or contact support.' if @corporate.nil?
      @properties = []
      properties.each do |key, value|
        property_params = value.extract! :name, :username, :useremail, :time_zone
        property = Property.create_property @corporate, property_params
        @properties << property if property
      end
    end

    if @corporate || @properties.count > 0
      # render :create
    else
      render :new
    end
  end

  def show
    @corporate = Corporate.find params[:id]
  end
end

app/views/admin/customers/_customer.html.slim
tr
  td
    .media-object= image_tag customer.avatar.url, class: 'img-circle', alt: customer.name
  td= customer.name
  td= customer.email
  td= customer.username
  td= customer.phone_number
  td= raw customer.all_properties.pluck(:name).join('<br/>')
  td
    = link_to 'Impersonate', impersonate_admin_customer_path(customer), method: :post, class: 'btn btn-success'

app/views/admin/customers/create.html.slim
h1 Corporate
- if @corporate
  p= @corporate.name

  h3 Corporate Users
  ul
    - @corporate.users.each do |user|
      li= [user.name, user.email].join(' - ')
- else
  p No Corporate

h1 Properties
ul
  - @properties.each do |property|
    li= property.name
    h4 Property Users
    - property.user_roles.unscoped.where(property_id: property.id).each do |user_role|
      - user = user_role.user
      - if user
        p= [user.name, user.email, user_role.role.name, user_role.title, user_role.order_approval_limit].join(' - ')

app/views/admin/customers/index.html.slim
.page-header.page-header-block
  .page-header-section
    h4.title.semibold All Customers
  .page-header-section
    .toolbar.clearfix
      = link_to 'Add New Customer', new_admin_customer_path, class: 'btn btn-primary'

.panel.panel-default
  .panel-body
    table.table.table-bordered.table-hover.nm
      thead
        tr
          th width="5%"
          th Name
          th Email
          th Username
          th Phone Number
          th Properties
          th
      tbody
        = render partial: 'customer', collection: @users, as: :customer

    .text-center
      = paginate @users

app/views/admin/customers/new.html.slim
- body_class 'admin-new-customer-page'

.page-header.page-header-block
  .page-header-section
    h4.title.semibold Setup New Customer

= simple_form_for :corporate, url: admin_customers_path, html: { class: 'panel panel-default', id: 'new-customer-form' } do |f|
  .panel-heading
    h3.panel-title New Customer
    .panel-toolbar.text-right
      = f.submit 'Create Customer', class: 'btn btn-success', data: {confirm: 'Do you want to create corporate?'}, id: 'create-customer'
  .panel-body
    .row
      .col-sm-6
        .panel.panel-default
          .panel-heading
            h3.panel-title Corporate Setup
          .panel-body
            .form-group
              = f.text_field :name, class: 'form-control', placeholder: 'Corporate Name'
            .form-group.mb0
              .row.mb5
                .col-sm-6.pr5
                  = f.text_field :username, class: 'form-control', placeholder: 'Full Name'
                .col-sm-6.pl5
                  = f.email_field :useremail, class: 'form-control', placeholder: 'User Email'
      .col-sm-6
        .panel.panel-default
          .panel-body
            .links.mb15
              = link_to 'javascript:void(0)', class: 'btn btn-primary add-new-property btn-block' do
                span.ico-plus-sign
                '
                | Add Property
            .panel-group.mb0#corporate-properties
    #create-spinner.indicator
      span.spinner.spinner3

script#property-template type="x-tmpl-mustache"
  .panel.panel-default.property-panel
    .panel-body
      .form-group
        = text_field_tag 'corporate[properties][{{index}}][name]', nil, class: 'form-control property-name', placeholder: 'Property Name'
      .form-group.mb0
        .row.mb5
          .col-sm-6.pr5
            = text_field_tag 'corporate[properties][{{index}}][username]', nil, class: 'form-control', placeholder: 'Full Name'
          .col-sm-6.pl5
            = email_field_tag 'corporate[properties][{{index}}][useremail]', nil, class: 'form-control property-email', placeholder: 'User Email'
          .col-sm-12.mt5
            = select_tag 'corporate[properties][{{index}}][time_zone]', time_zone_options_for_select(nil, ActiveSupport::TimeZone.us_zones), prompt: "Select Timezone", class: "form-control timezone-selector"

app/views/admin/customers/show.html.slim
h1 Corporate
p= @corporate.name

h3 Corporate Users
ul
  - @corporate.users.each do |user|
    li= [user.name, user.email].join(' - ')

h1 Properties
ul
  - @corporate.properties.each do |property|
    li= property.name
    h4 Property Users
    - property.user_roles.unscoped.where(property_id: property.id).each do |user_role|
      - user = user_role.user
      - if user
        p= [user.name, user.email, user_role.role.name, user_role.title, user_role.order_approval_limit].join(' - ')