config/routes.rb
Lodgistics::Application.routes.draw do
  apipie
  require 'sidekiq/web'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  authenticate :admin do
    mount Blazer::Engine, at: "admin/intelligence"
  end

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    # registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }, skip: [:registrations]

  %w( 403 404 500 ).each do |code|
    get code, to: "errors#show", code: code
  end

  namespace :api do
    resource :auth, only: [:create, :destroy], controller: :auth
    resource :profile, only: [:show, :update], controller: :profile
    resources :task_lists, only: [:index, :show, :destroy] do
      collection do
        get :activities
        get :all
      end
      member do
        post :start_resume
      end
    end
    resources :task_list_records, only: [:show] do
      member do
        post :finish
        post :review
      end
    end
    resources :task_item_records, only: [] do
      member do
        post :complete
        post :reset
      end
    end
    resources :task_items, only: [:create, :update, :destroy]
    resources :locations, only: [:index]
    resources :roles, only: [:index]
    resources :properties, only: [:create, :index]
    resources :in_app_notifications, only: [:index]
    resources :departments, only: [:index]
    resources :public_areas, only: [:index, :show] do
      resources :checklist_items, only: [ :index ]
      collection do
        get :checklist_items
      end
    end
    resources :rooms, only: [] do
      collection do
        get :checklist_items
      end
    end
    resources :acknowledgements, only: [:index, :create, :show] do
      collection do
        get :sent
        get :received
      end
    end
    resources :feeds, only: [:index, :create, :show, :update] do
      resources :work_orders, only: [ :create ]
      collection do
        get :broadcasts
        get :follow_ups
      end
    end
    get '/broadcasts' => 'feeds#broadcasts'
    resources :chats, only: [:create, :update, :index] do
      collection do
        get :group_only
        get :private_only
      end
      member do
        get :messages
      end
    end
    resources :chat_messages, only: [ :index, :create, :show ] do
      resources :work_orders, only: [ :create ]
      collection do
        get :updates
        put :mark_read_mass
      end
      member do
        put :mark_read
      end
    end
    resources :users, only: [:index, :show, :update, :create] do
      member do
        get :roles_and_departments
        put :confirm
      end
      collection do
        post :invite
        post :multi_invite
        get :request_confirm
      end
    end
    resources :mentions, only: [:index, :update] do
      collection do
        put :snooze
        put :unsnooze
        put :clear
      end
    end
    resources :work_orders, only: [:index, :create, :show, :update] do
      member do
        put :close
      end

      collection do
        get :assignable_users
      end
    end
    resources :checklist_items, only: [:index]
    resources :chat_mentions, only: [:update]
    resource :passwords, only: [:create, :update]
    resources :permissions, only: [:index]
    resources :push_notification_settings, only: [:index]
    resource :push_notification_settings, only: [:update]
    get '/s3_sign', to: 'auth#s3_sign'
    resources :check_for_app_update, only: [:index]
  end
  get '/login/:auth_token' => 'login#create'
  get '/how-to-videos' => 'videos#how_to_videos'

  resources :chats, only: [:show, :index, :new, :create]
  resources :messages, controller: :chats, only: [ :show, :index, :new, :create ]
  resources :chat_messages, only: [:create]
  resources :task_lists, only: [:index, :show, :new, :edit, :create, :update] do
    collection do
      get :activities
      get :setup
    end
  end

  namespace :corporate do
    root to: 'pages#dashboard'
    resources :settings, only: [:index]
    resources :property_connections, only: [:show, :update]
    resources :purchase_requests, only: [:edit, :update], path: 'requests'
    get '/spend_budget_by_hotel_data' => 'pages#spend_budget_by_hotel', as: 'spend_budget_by_hotel_data'
    get '/work_order_clouds' => 'pages#work_order_clouds', as: 'work_order_clouds'
    get '/open_work_order_by_hotel' => 'pages#open_work_orders_by_hotel', as: 'open_work_orders_by_hotel'
  end

  namespace :maintenance do
    root to: 'pages#dashboard' # probably need to move it under /dashboard, @HUGO
    get :setup, to: 'setup#index', as: :setup
    get '/setup/rooms', to: 'setup#rooms', as: :setup_rooms
    get '/setup/public_areas', to: 'setup#public_areas', as: :setup_public_areas
    get '/setup/equipment', to: 'setup#equipment', as: :setup_equipment
    resources :rooms, only: [:show, :index, :create, :update] do
      get :inspection, on: :collection
      get :inspect, on: :member
    end
    resources :checklist_items, only: [:index, :create, :update,:destroy]
    resources :cycles, only: [:create] do
      post :create_next, on: :collection
    end
    resources :checklist_item_maintenances, only: [:index, :create, :destroy] do
      member do
        post :inspect
        delete :cancel_inspect
      end

      collection do
        get :equipment
      end
    end
    resources :public_areas, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :checklist_items
        get :inspection
      end
      get :inspect, on: :member
    end
    resources :records, only: [:index, :update, :show, :destroy] do
      member do
        post :complete_inspection
        post :cancel_inspection
      end
    end
    resources :work_orders do
      get :export, on: :collection
    end
    resources :materials, only: [:index, :create, :update, :destroy]
    resources :equipment_types, only: [:index, :create, :update, :destroy] do
      resources :equipment_checklist_items, only: [:index, :create, :show, :update, :destroy]
    end
    resources :equipments, only: [:index, :show, :create, :update, :destroy]

    get '/week_vs_completed_rooms_data' => 'pages#week_vs_completed_rooms_data', as: 'week_vs_completed_rooms_data'
    get '/pm_room_progress_data' => 'pages#pm_room_progress_data', as: 'pm_room_progress_data'
  end

  namespace :admin do
    root to: 'pages#dashboard'
    resources :users, only: [:edit, :update]
    resources :customers, only: [:index, :new, :create, :show] do
      member do
        post :impersonate
      end
    end
  end

  devise_for :admins, path: 'admin', controllers: {
                        sessions: 'admin/sessions',
                        passwords: 'admin/passwords'
                      }

  resource :corporate_connections

  get :spend_vs_budgets_data, to: 'pages#spend_vs_budgets_data'
  get :s3_sign, to: 'pages#s3_sign'

  authenticated :user do
    root 'pages#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'pages#dashboard', as: :admin_authenticated_root
  end

  devise_scope :user do
    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
    namespace :users, as: :user do
      put "/confirm" => "confirmations#confirm", as: :confirm
      put '/switch_current_property', to: 'sessions#switch_current_property', as: :switch_current_property
      resource :registration, only: [:edit, :update]
    end
  end
  resources :property_settings, path: 'settings', only: [:index]
  resources :categories, :locations, :lists do
    get 'rearrange', on: :member
    get 'destroy', on: :collection, as: 'destroy'
  end
  resources :items do
    collection do
      get 'start_order'
      get 'edit_multiple_tags'
      put 'update_multiple_tags'
      get :new_import
      post :import
      get 'destroy', as: 'destroy'
    end
  end
  resources :permissions, only: [:index] do
    collection do
      post 'update_all'
    end
  end
  resources :properties, only: [:show, :index, :update]
  resources :tags do
    get 'rearrange', on: :member
  end
  resources :purchase_orders, except: [:edit, :new, :create], path: 'orders' do
    member do
      post :send_fax, to: 'fax#create'
      get :fax_status, to: 'fax#show'
      post :update_fax, to: 'fax#update'
      post :send_email, to: 'email#create'
      post :send_vpt, to: 'vpt#create'
      get :print
    end
  end
  resources :purchase_receipts, only: [:new, :create], path: 'receipts'
  resources :purchase_requests, path: 'requests' do
    member do
      get :inventory_print
    end
  end
  resources :users do
    member do
      get :change_password
    end

    collection do
      post :valid_username
      post :confirm_username
    end
  end
  resources :work_order_messages, controller: :messages
  resources :budgets
  resources :schedules, only: [:create, :update, :destroy]
  resources :occurrences, only: [:create]

  resources :reports do
    member do
      put :favorite
    end
    collection do
      get :favorites
      #get *Report.pluck(:permalink).map{|p| p + '_data'} if Report.any?
      get :trending_cloud
      scope :render do
        get :vendor_spend
        get :category_spend
        get :items_consumption
        get :item_orders_chart_data
        get :items_spend
        get :item_price_variance
        get :inventory_vs_ordering
        get :maintenance_work_orders
        get :pm_productivity_report
        get :maintenance_pm_productivity_data
        get :room_pm_progress_data
        get :work_order_productivity_data
        get :guest_room_pm_analysis
        get :public_area_pm_analysis
        get :equipment_pm_analysis
        get :work_order_trendings
      end
    end
  end


  resources :vendors
  resources :room_types
  resources :departments

app/models/maintenance.rb
module Maintenance
  def self.table_name_prefix
    'maintenance_'
  end
end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < Api::BaseController
  include RoomsDoc

  skip_before_action :set_resource

  def checklist_items
    area_checklist_items = Maintenance::ChecklistItem.for_property_id(Property.current_id).by_type('rooms').areas
    result = area_checklist_items.map do |area_checklist_item|
      {
        id: area_checklist_item.id,
        name: area_checklist_item.name,
        checklist_items: area_checklist_item.checklist_items.map { |i| i.as_json(only: [:id, :name]) }
      }
    end
    render json: result
  end

  private

end

app/controllers/maintenance/base_controller.rb
class Maintenance::BaseController < ApplicationController
  before_action :check_permissions
  before_action :check_current_cycles_are_finished

  add_breadcrumb I18n.t("controllers.maintenance.root"), :maintenance_root_path

  private

  def check_permissions
    authorize :access, :maintenance?
  end

  # returns an array of cycles that are finished by the moment of checking
  # example: [:room]
  def check_current_cycles_are_finished
    finished_cycles = Maintenance::Cycle::CYCLE_TYPES
    .map{ |c_type| current_cycle(c_type) }.compact
    .select{ |cycle| cycle.is_over? }
    # to test messages uncomment next line:
    # finished_cycles = [current_cycle(:room), current_cycle(:public_area)]
    messages = render_to_string(partial: 'maintenance/shared/cycle_expired_alert', locals: {finished_cycles: finished_cycles})
    flash[:sticky_messages] = [[:alert, messages]] if finished_cycles.any?
  end

  def send_notification_and_mail_to_assignee(work_order)
    if @work_order.assigned_to
      MaintenanceWorkOrderMailer.work_order_notification_to_assignee(work_order).deliver!
      Notification.assigned_work_order(work_order)
      WorkOrderWorker.perform_async(work_order.id)
    end
  end

  def authorize_maintenance
    authorize :access, :pm?
  end

  def authorize_inspection
    authorize :access, :inspection?
  end

  def authorize_work_order
    authorize :access, :work_order?
  end

  def authorize_pm_setup
    authorize :access, :pm_setup?
  end

end

app/controllers/maintenance/checklist_item_maintenances_controller.rb
class Maintenance::ChecklistItemMaintenancesController < Maintenance::BaseController

  before_action :get_maintainable, only: [:index, :create, :inspect, :equipment]

  def index
    render json: @maintainable.maintenance_records.find(params[:record_id]).to_json(
         include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
      ), status: 200
  end

  def equipment
    render json: @maintainable.maintenance_records.where(id: params[:record_id]).first.to_json(
               include: { checklist_item_maintenances: { include: [:work_order, :inspection_work_order] } }
           ), status: 200
  end

  def create
    if !policy(Maintenance::ChecklistItemMaintenance).single_click_pm? && params[:checklist_item_ids] && params[:checklist_item_ids].count > 1
      render json: {message: 'You are not authroized to do single click PM'}, status: 401 and return
    end
    if params[:record_id]
      @record = @maintainable.maintenance_records.find params[:record_id]
    else
      @record = @maintainable.maintenance_records.for_cycle(params[:cycle_id])
    end
    checklist_item_ids = (params[:checklist_item_ids] || []).map(&:to_i) - @record.checklist_item_maintenances.pluck(:maintenance_checklist_item_id)
    item_maintenance_ids = []
    checklist_item_ids.each do |item_id|
      checklist_item_maintenance = @record.checklist_item_maintenances.find_or_initialize_by(maintenance_checklist_item_id: item_id)

      if params[:status] == Maintenance::ChecklistItemMaintenance::STATUS_ISSUES.to_s
        checklist_item_maintenance.update_attributes status: params[:status]

        work_order = Maintenance::WorkOrder.new(work_order_params)
        work_order.checklist_item_maintenance = checklist_item_maintenance
        work_order.opened_by = current_user
        work_order.maintainable = @maintainable
        work_order.opened_at = Time.current
        work_order.status = Maintenance::WorkOrder::STATUS_OPEN
        work_order.assigned_to_id = current_user.wo_assignable_id
        work_order.priority = 'l'
        work_order.save
      else
        checklist_item_maintenance.update_attributes(status: params[:status], comment: params[:comment])
      end
      item_maintenance_ids << checklist_item_maintenance.id
    end

    @checklist_item_maintenances = @record.checklist_item_maintenances.where(id: item_maintenance_ids)
    render json: @checklist_item_maintenances.to_json(include: :work_order), status: 200
  end

  def inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_detail = @checklist_item_maintenance.build_inspection_detail
    @work_order = @inspection_detail.build_work_order
    @work_order.maintainable = @maintainable
    @work_order.description = params[:comment]
    @work_order.opened_by = current_user
    @work_order.opened_at = Time.current
    @work_order.status = Maintenance::WorkOrder::STATUS_OPEN
    @work_order.priority = 'l'
    @work_order.checklist_item_maintenance = @checklist_item_maintenance
    completed_by = @checklist_item_maintenance.maintenance_record.completed_by
    @work_order.assigned_to_id = (completed_by && completed_by.wo_assignable_id) || Maintenance::WorkOrder::UNASSIGNED

    @inspection_detail.save

    render json: @inspection_detail.to_json(include: :work_order), status: 200
  end

  def cancel_inspect
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @inspection_work_order = @checklist_item_maintenance.inspection_work_order
    @inspection_work_order.destroy

    render json: @checklist_item_maintenance.id, status: 200
  end

  def destroy
    @checklist_item_maintenance = Maintenance::ChecklistItemMaintenance.find params[:id]
    @checklist_item_maintenance.destroy
    render json: params[:id], status: 200
  end

  private

  def get_maintainable
    @maintainable = params[:maintainable_type].classify.constantize.find(params[:maintainable_id])
  end

  def work_order_params
    params.require(:maintenance_work_order).permit(
      :status, :description, :priority, :assigned_to_id, :maintainable_id, :maintainable_type, :other_maintainable_location, :due_to_date,
      attachments_attributes: [:id, :file, :_destroy ]
    )
  end

end

app/controllers/maintenance/checklist_items_controller.rb
class Maintenance::ChecklistItemsController < Maintenance::BaseController
  before_action :set_maintenance_checklist_item,only: [:update,:destroy]
  skip_before_action :check_current_cycles_are_finished

  def index
    @checklist_items = Maintenance::ChecklistItem.for_property_id(Property.current_id).areas_with_subcategories
    render json: @checklist_items.to_json
  end

  def create
    p = checklist_item_params.merge!(property_id: Property.current_id)
    @checklist_item = Maintenance::ChecklistItem.new(p)
    @checklist_item.user_id = current_user.id
    @checklist_item.save
    render json: @checklist_item.to_json(only: [:id, :name, checklist_items: []]), status: 200
  end

  def update
    @checklist_item.update checklist_item_params
    render body: nil, status: 200
  end

  def destroy
    @checklist_item.update_attribute(:is_deleted, true)
    render body: nil, status: 200
  end

  private

  def set_maintenance_checklist_item
    @checklist_item = Maintenance::ChecklistItem.find params[:id]
  end

  def checklist_item_params
    params.require(:checklist_item).permit(
        :name,
        :area_id,
        :maintenance_type,
        :public_area_id,
        :area_row_order_position,
        :item_row_order_position,
        :public_area_row_order_position
    )
  end
end

app/views/maintenance/rooms/inspect.html.slim
- body_class 'room-inspect-page'

.page-header.page-header-block
  .page-header-section
    h4.title.semibold= t('.header', room_number: @room.room_number)
  .page-header-section.clearfix
    .actions.pull-right
      = link_to_with_icon 'ico-stack-checkmark', t('.complete_inspection'),
                          complete_inspection_maintenance_record_path(@record, maintenance_maintenance_record: {status: Maintenance::MaintenanceRecord::STATUS_COMPLETED}),
                          class: 'btn btn-primary', data: {confirm: t('.complete_inspection_confirm')}, method: :post
      = link_to_with_icon 'ico-clock', t('.continue_later'), inspection_maintenance_rooms_path, class: 'btn btn-primary', data: {confirm: t('.complete_inspection_confirm')}, method: :get
      = link_to_with_icon 'ico-close2', t('.cancel_inspection'), cancel_inspection_maintenance_record_path(@record), class: 'btn btn-danger', data: {confirm: t('.complete_inspection_confirm')}, method: :post
.row
  .col-sm-12
    table.table#room-inspect-table data-room-id=(@room.id) data-cycle-id=(current_cycle(:room).id) data-room-number=(@room.room_number) data-record-id=(@record.id)
      thead.hidden
        tr
          th
          th
      tbody
    .indicator.inline
      span.spinner
script#area-checklist-template type="x-tmpl-mustache"
  .area-detail-div
    table.table-condensed.nm.area-detail-table
      | {{#subcategories}}
      tr data-item-id="{{maintenance_id}}"
        td.checklist-item-name
          .maintenance-status
            | {{#no_issues}}
            = link_to 'javascript:void(0)', class: 'maintenance-status-icon no-issues' do
              i.ico-ok.fa-fw
            | {{/no_issues}}
            | {{#fixed}}
            = link_to 'javascript:void(0)', class: 'maintenance-status-icon fixed' do
              i.ico-wand.fa-fw
            | {{/fixed}}
            | {{#issues}}
            = link_to 'javascript:void(0)', class: 'maintenance-status-icon work-order' do
              i.ico-tools.fa-fw
            | {{/issues}}
          .maintenance-description
            span= '{{name}}'
            | {{#fixed}}
            dl.dl-horizontal.maintenance-detail
              dt Fixed:
              dd= '{{comment}}'
            | {{/fixed}}
            | {{#issues}}
            dl.dl-horizontal.work-order-detail.no-wrapping
              dt Work Order:
              dd &#35;{{work_order.id}}
            dl.dl-horizontal.work-order-detail
              dt.no-width
              dd
                | {{work_order.description}}
            | {{/issues}}
            | {{#inspected}}
            dl.dl-horizontal.work-order-detail
              dt Work Order:
              dd &#35;{{inspection_work_order.id}}
            dl.dl-horizontal.work-order-detail
              dt.no-width
              dd
                | {{inspection_work_order.description}}
            | {{/inspected}}
        td.maintenance-actions width=80
          = link_to '{{cancel_path}}',
                    class: 'room-checklist-action spot-check {{^inspected}}inactive{{/inspected}} {{#inspected}}active{{/inspected}}', method: :delete,
                    data: {status: Maintenance::ChecklistItemMaintenance::STATUS_NO_ISSUES, confirm: t('.inspect_item_confirm'), remote: true} do
            i.ico-tools.fa-fw
      | {{/subcategories}}

#room-inspection-work-order-modal.modal.fade
  .modal-dialog
    form.modal-content id="room-work-order-form" data-parsley-validate=true
      .modal-header
        .cell.text-center
          button.close data-dismiss="modal" type="button" ×
          h4.semibold.text-primary.modal-title.work-order-title= t('.work_order_header')
      .modal-body
        .form-group
          textarea class="form-control" rows=5 placeholder=(t('.work_order_placeholder')) id="work-order-comment" required=true data-parsley-maxlength=500
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"= t('.cancel_form')
        button.btn.btn-primary type="submit" id="work-order-form-submit"= t('.work_order_submit')

app/views/maintenance/rooms/inspection.html.slim
- body_class 'room-inspection-page'

.page-header.page-header-block
  .page-header-section
    h4.title.semibold= t('.header')
- if current_cycle(:room)
  .row
    .col-md-4
      .table-layout.animation.delay.animating.fadeInDown
        .col-xs-4.panel.bgcolor-info.text-center
          .ico-users3.fsize24
        .col-xs-8.panel
          .panel-body.text-center
            h3.semibold.text-muted.nm= current_cycle(:room).ordinality_number.ordinalize
            p.semibold.text-primary.mb0.mt5.ellipsis= raw t('.current_cycle')

    .col-md-4
      .table-layout.animation.delay.animating.fadeInDown
        .col-xs-4.panel.bgcolor-primary.text-center
          .ico-bed.fsize24
        .col-xs-8.panel
          .panel-body.text-center
            h3.semibold.nm.text-muted
              span= current_cycle(:room).rooms_inspected.count
              span.small= " / #{current_property.target_inspection_count}"
            p.semibold.text-primary.mb0.mt5.ellipsis= raw t('.guest_rooms_inspected')

    .col-md-4
      .table-layout.animation.delay.animating.fadeInDown
        .col-xs-4.panel.bgcolor-warning.text-center
          .ico-calendar5.fsize24
        .col-xs-8.panel
          .panel-body.text-center
            h3.semibold.nm.text-muted= current_cycle(:room).days_to_finish
            p.semibold.text-primary.mb0.mt5.ellipsis= raw t('.days_remaining')
.row
  .col-sm-12.col-md-12
    table.table.table-bordered.table-hover#rooms-inspection-table
      thead
        tr
          th= t('.choose_room_from_list')
      tbody
    .indicator.inline
      span.spinner
script#room-inspect-template type="x-tmpl-mustache"
  .room-detail.clearfix
    .room-name
      span= 'Guest Room #{{room_number}}'
      dl.dl-horizontal.room-inspection-info.no-wrapping
        dt Completed By:
        dd= '{{completed_by}}'
      dl.dl-horizontal.room-inspection-info.no-wrapping
        dt Completed On:
        dd= '{{completed_on}}'
      dl.dl-horizontal.room-inspection-info.no-wrapping
        dt Fixes:
        dd= '{{fixed}}'
      dl.dl-horizontal.room-inspection-info.no-wrapping
        dt Work Orders:
        dd= '{{work_orders}}'
    .room-inspection-actions
      | {{^completed}}
      | {{^in_inspection}}
      = link_to 'Inspect', '/maintenance/rooms/floor{{floor}}-room{{room_number}}/inspect', class: 'start-maintenance btn btn-primary btn-outline'
      | {{/in_inspection}}
      | {{#in_inspection}}
      = link_to 'Continue', '/maintenance/rooms/floor{{floor}}-room{{room_number}}/inspect', class: 'start-maintenance btn btn-primary btn-outline'
      | {{/in_inspection}}
      | {{/completed}}
      | {{#completed}}
      .text-right
        span.label.label-success Inspected
      | {{/completed}}
      .room-inspection-info.text-left
        div
          b Last Inspection:
        | {{#ever_inspected}}
        div
          | {{last_inspected_on}}
        div
          b By
          |  {{last_inspected_by}}
        div Inspected {{inspected_count}} times
        div in {{cycles_count}} previous cycles
        | {{/ever_inspected}}
        | {{^ever_inspected}}
        div.small No Inspection Done
        | {{/ever_inspected}}

app/views/maintenance/rooms/show.html.slim
- body_class 'room-maintenance-page'

.page-header.page-header-block
  .page-header-section
    h4.title.semibold= t('.header', room_number: @room.room_number)
  .page-header-section
    .actions.pull-right
      = link_to_with_icon 'ico-clock', t('.continue_later'), maintenance_rooms_path, class: 'btn btn-primary', data: {confirm: t('.continue_later_confirm')}, method: :get
      '
      = link_to_with_icon 'ico-close2', t('.cancel'), maintenance_record_path(@record), class: 'btn btn-danger', data: {confirm: t('.cancel_confirm')}, method: :delete
.row
  .col-sm-12
    table.table#area-checklist-table data-room-id=(@room.id) data-cycle-id=(current_cycle(:room).id) data-room-number=(@room.room_number) data-record-id=(@record.id) permitted-single-click-pm=(policy(Maintenance::ChecklistItemMaintenance).single_click_pm?)
      thead.hidden
        tr
          th
          th
      tbody
    .indicator.inline
      span.spinner

script#area-checklist-template type="x-tmpl-mustache"
  .area-detail-div
    table.table-condensed.nm.area-detail-table
      | {{#subcategories}}
      tr data-item-id="{{id}}"
        td.checklist-item-name
          span= '{{name}}'
          | {{#fixed}}
          dl.dl-horizontal.maintenance-detail
            dt Fixed:
            dd= '{{comment}}'
          | {{/fixed}}
          | {{#issues}}
          dl.dl-horizontal.work-order-detail
            dt Work Order:
            dd &#35;{{work_order.id}}
          | {{/issues}}
        td.maintenance-actions width=170
          = link_to '{{cancel_path}}',
                    class: 'room-checklist-action no-issues {{#no_maintenance}}inactive{{/no_maintenance}} {{#no_issues}}active{{/no_issues}}',
                    data: {status: Maintenance::ChecklistItemMaintenance::STATUS_NO_ISSUES, confirm: '{{cancel_confirm_msg}}', remote: true, method: :delete} do
            i.ico-ok.fa-fw
          '
          = link_to '{{cancel_path}}',
                    class: 'room-checklist-action issue-fixed {{#no_maintenance}}inactive{{/no_maintenance}} {{#fixed}}active{{/fixed}}',
                    data: {status: Maintenance::ChecklistItemMaintenance::STATUS_FIXED, confirm: '{{cancel_confirm_msg}}', remote: true, method: :delete} do
            i.ico-wand.fa-fw
          '
          = link_to 'javascript:void(0)',
                    class: 'room-checklist-action work-order {{#no_maintenance}}inactive{{/no_maintenance}} {{#issues}}active{{/issues}}',
                    data: {status: Maintenance::ChecklistItemMaintenance::STATUS_ISSUES} do
            i.ico-tools.fa-fw
      | {{/subcategories}}

#room-maintenance-comment-modal.modal.fade
  .modal-dialog
    form.modal-content id="room-fixed-form" data-parsley-validate=true
      = render 'maintenance/shared/request_wo_modal_content'

#room-maintenance-completed-modal.modal.fade
  .modal-dialog
    = form_for @record, url: maintenance_record_path(@record), html: { class: 'modal-content' } do |f|
      .modal-header
        .cell.text-center
          h4.semibold.text-primary.modal-title= t('.maintenance_completed_header')
      .modal-body
        = f.hidden_field :status, value: Maintenance::MaintenanceRecord::STATUS_FINISHED
        p#maintenance-information
      .modal-footer
        = f.submit 'OK', class: 'btn btn-primary btn-expanded'